// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.10.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String syncGreet({required String name, dynamic hint}) =>
    RustLib.instance.api.syncGreet(name: name, hint: hint);

Future<String> asyncGreetWithCallback(
        {required String name,
        required FutureOr<void> Function(String) logger,
        dynamic hint}) =>
    RustLib.instance.api
        .asyncGreetWithCallback(name: name, logger: logger, hint: hint);

Future<String> asyncGreetWithCallbackNoAwait(
        {required String name,
        required FutureOr<void> Function(String) logger,
        dynamic hint}) =>
    RustLib.instance.api
        .asyncGreetWithCallbackNoAwait(name: name, logger: logger, hint: hint);

Future<String> asyncGreet({required String name, dynamic hint}) =>
    RustLib.instance.api.asyncGreet(name: name, hint: hint);
