// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

Future<String> asyncGreet(
        {required String name,
        required FutureOr<void> Function(String) logger,
        dynamic hint}) =>
    RustLib.instance.api.asyncGreet(name: name, logger: logger, hint: hint);

Future<String> asyncNoAwaitGreet(
        {required String name,
        required FutureOr<void> Function(String) logger,
        dynamic hint}) =>
    RustLib.instance.api
        .asyncNoAwaitGreet(name: name, logger: logger, hint: hint);
